### ISSUE TITLE
Update for WinJS 4.0

### ISSUE THREAD

**Issue by RichiCoder1** [winjs/knockout-winjs#1]
This appears to still be built against a much outdated version of WinJS. Would love to use this.

**Comment by James-Parsons** [comment]
Supposedly, its coming.

**Comment by RichiCoder1** [comment]
I hope so. I've had to manually do this bridge my self for a number controls and would love an official, comprehensive solution sooner than later. The fact that this was put here and then untouched for a month (if not technically longer) doesn't inspire much confidence though.

**Comment by mikewjackson** [comment]
Thank you for the feedback, we are actively investigating updating our knockout-winjs bridge to work with WinJS4.0
