### ISSUE TITLE
Possible bug in bindingListWatch

### ISSUE THREAD

**Issue by rigdern** [winjs/knockout-winjs#3]
I noticed that `bindingListWatch` was modified in the version of knockout-winjs used in the CharMap //build demo:

https://github.com/MicrosoftEdge/CharMap/blob/master/js/lib/knockout-winjs.js

If you diff that file with the initial check in of knockout-winjs in this repo, you'll see there are a few differences:

![image](https://cloud.githubusercontent.com/assets/199935/8467074/9925dcb8-200e-11e5-96f1-1c5ef23b7110.png)

We should investigate why those changes were made and make a fix in this repo if needed.

**Comment by ghost** [comment]
Fixed with fbdbe4f7dbc855535387ab99b8cda5ffcad783ed
